[package]
name = "chriswhealy/sha256"
version = "1.0.0"
license = "MIT"
description = "Calculate the SHA256 hash of a local file"
repository = "https://github.com/ChrisWhealy/wasm_sha256"
readme = "https://github.com/ChrisWhealy/wasm_sha256?tab=readme-ov-file#wasmer"

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = "sha256"
source = "./bin/sha256_opt.wasm"
abi = "wasi"

[[command]]
name = "sha256"
module = "sha256"
runner = "wasi"
