[package]
name = "chriswhealy/sha256"
version = "1.4.1"
license = "MIT"
description = "Calculate the SHA256/224 hash of a local file in WebAssembly Text"
repository = "https://github.com/ChrisWhealy/wasm_sha256"
readme = "./README.md"

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = "sha256"
source = "./bin/sha256.opt.wasm"
abi = "wasi"

[[command]]
name = "sha256"
module = "sha256"
runner = "wasi"

[[command]]
name = "sha224"
module = "sha256"
runner = "wasi"
